import 'package:bnflp_wireframe/data/dataTypes.dart';

// Change this stuff if wanted
List<ButtonData> buttonDataList = [
  ButtonData(title: "Home", route: '/'),
  ButtonData(title: "Galleries", route: '/galleries'),
  ButtonData(title: "My Cart", route: '/cart'),
  ButtonData(title: "About Me", route: '/aboutMe'),
];


List<AwardData> awards = [
  AwardData(title: "Best Photographer 2020", description: "Awarded for outstanding photography in 2020"),
  AwardData(title: "Creative Excellence 2019", description: "Recognized for creative excellence in photography"),
  AwardData(title: "Top Portrait Photographer 2018", description: "Awarded for exceptional portrait photography"),
  AwardData(title: "Innovative Photographer 2017", description: "Recognized for innovative techniques in photography"),
  AwardData(title: "Best Landscape Photographer 2016", description: "Awarded for outstanding landscape photography"),
];

// AUTOGENERATED VARIABLES BELOW
List<CartItemData> shoppingCart = [];